In [2]:
import os
import sys
import math
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import pickle

#Sites de Iteresse:
#https://zenodo.org/records/11185049
#https://github.com/tbrugz/geodata-br/blob/master/geojson/geojs-100-mun.json

# Menu
<a name="navegacao"></a>

## 1) [Preparação dos dados](#parte1)
- 1.1 [Leitura dos Dados de Exemplo](#exemplo)
- 1.2 [Leitura das Coordenadas](#coordenadas)
- 1.3 [Mapa do Exemplo](#mapaexemplo)
- 1.4 [Leitura dos Dados de Fraudes](#dadosfraudes)
- 1.5 [Mapa das Fraudes de PF](#mapafraudepf)
- 1.6 [Mapa das Fraudes de PJ](#mapafraudepj)

- https://zenodo.org/records/11185049

<a name="exemplo"></a>

## 1.1) Leitura dos Dados de Exemplo

In [16]:
# Importando bibliotecas necessárias
import pandas as pd


# Importando o conjunto de dados
tipos = {'CODMUN':'str' , 'CNPJ':'str', 'CODMUN_IBGE' : 'str'}

estban = pd.read_csv('./dados/202402_ESTBAN_AG.CSV' , encoding='latin-1',sep=";", dtype=tipos)

estban2 = estban[estban['UF']=='RS'].copy()

C:\Users\patrick.franco\AppData\Local\Temp\ipykernel_21608\818409877.py:8: DtypeWarning: Columns (11,12,13,15,16,17,18,22,24,30,31,34,37,38,40,41,42,46,47,51) have mixed types. Specify dtype option on import or set low_memory=False.
  estban = pd.read_csv('./dados/202402_ESTBAN_AG.CSV' , encoding='latin-1',sep=";", dtype=tipos)

In [18]:
estban2.head()

,#DATA_BASE,UF,CODMUN,MUNICIPIO,CNPJ,NOME_INSTITUICAO,AGENCIA,VERBETE_110_DISPONIBILIDADES,VERBETE_111_CAIXA,VERBETE_112_DEPOSITOS_BANCARIOS,...,VERBETE_470_INST_FINANCEIROS_DERIVATIVOS,VERBETE_480_OBRIGACOES_POR_RECEBIMENTO,VERBETE_481_IOF + VERBETE_482_CONTRIBUICOES_PREVIDENCIARIAS + VERBETE_483_TRIBUTOS_ESTAD_E_MUNICIPAIS + VERBETE_484_TRIBUTOS_FEDERAIS + VERBETE_485_FGTS + VERBETE_487_DEMAIS_RECEBIMENTOS,VERBETE_490_CHEQUES_ADMINISTRATIVOS + VERBETE_500_OUTRAS_OBRIGACOES,VERBETE_610_PATRIMONIO_LIQUIDO,VERBETE_710_CONTAS_DE_RESULTADO,VERBETE_711_CONTAS_CREDORAS,VERBETE_712_CONTAS_DEVEDORAS,VERBETE_899_TOTAL_DO_PASSIVO,CODMUN_IBGE
9415,202402,RS,57699,ACEGUA,92702067,BCO DO ESTADO DO RS S.A.,'92702067063783,220934,220934,0,...,0,0,0,42055,0,301678,571089,-269411,10643715,4300034
9416,202402,RS,45522,AGUA SANTA,0,BCO DO BRASIL S.A.,'00000000116815,959056,959056,0,...,6,75914,75914,65790,0,1782489,2116250,-333760,161769601,4300059
9417,202402,RS,45522,AGUA SANTA,92702067,BCO DO ESTADO DO RS S.A.,'92702067063945,210360,210360,0,...,0,0,0,30335,0,173855,405445,-231590,9385021,4300059
9418,202402,RS,34090,AGUDO,360305,CAIXA ECONOMICA FEDERAL,'00360305129220,789109,789109,0,...,0,185425,185425,14251354,0,466227,1416886,-950659,60874805,4300109
9419,202402,RS,34090,AGUDO,92702067,BCO DO ESTADO DO RS S.A.,'92702067024451,777230,777230,0,...,0,0,0,44090,0,167753,804790,-637037,22600812,4300109

In [19]:
estban2.shape

(1426, 53)

In [20]:
estban2.describe()

,#DATA_BASE,VERBETE_110_DISPONIBILIDADES,VERBETE_111_CAIXA,VERBETE_112_DEPOSITOS_BANCARIOS,VERBETE_113_BACEN_RESERV_BANC_EM_ESPECIE,VERBETE_141_CORRESPONDENTES_NO_EXTERIOR + VERBETE_142_CORRESPONDENTES_NO_PAIS,VERBETE_162_FINANCIAMENTOS,VERBETE_163_FIN_RURAIS_AGRICUL_CUST/INVEST,VERBETE_167_FINANCIAMENTOS_AGROINDUSTRIAIS,VERBETE_171_OUTRAS_OPERACOES_DE_CREDITO,...,VERBETE_420_DEPOSITOS_DE_POUPANCA,VERBETE_431_DEPOSITOS_INTERFINANCEIROS,VERBETE_432_DEPOSITOS_A_PRAZO,VERBETE_441_CORRESPONDENTES_NO_EXTERIOR + VERBETE_442_CORRESPONDENTES_NO_PAIS,VERBETE_470_INST_FINANCEIROS_DERIVATIVOS,VERBETE_480_OBRIGACOES_POR_RECEBIMENTO,VERBETE_481_IOF + VERBETE_482_CONTRIBUICOES_PREVIDENCIARIAS + VERBETE_483_TRIBUTOS_ESTAD_E_MUNICIPAIS + VERBETE_484_TRIBUTOS_FEDERAIS + VERBETE_485_FGTS + VERBETE_487_DEMAIS_RECEBIMENTOS,VERBETE_710_CONTAS_DE_RESULTADO,VERBETE_711_CONTAS_CREDORAS,VERBETE_712_CONTAS_DEVEDORAS
count,1426.0,1.426000e+03,1.426000e+03,1.426000e+03,1.426000e+03,1.426000e+03,1.426000e+03,1.426000e+03,1.426000e+03,1.426000e+03,...,1.426000e+03,1.426000e+03,1.426000e+03,1.426000e+03,1.426000e+03,1.426000e+03,1.426000e+03,1.426000e+03,1.426000e+03,1.426000e+03
mean,202402.0,2.691102e+06,1.866224e+06,8.210152e+05,3.862065e+03,3.302341e+04,7.976407e+06,5.335672e+07,6.209078e+04,1.784755e+05,...,6.114234e+07,1.213130e+07,9.630509e+07,2.675771e+04,2.722413e+05,6.007647e+05,6.007647e+05,1.209175e+06,7.123567e+06,-5.914392e+06
std,0.0,3.176078e+07,1.870612e+07,1.660114e+07,1.376352e+05,3.135661e+05,7.502340e+07,6.357863e+08,1.145097e+06,7.692735e+05,...,7.366360e+08,3.998152e+08,1.463303e+09,1.001029e+06,9.930027e+06,1.003425e+07,1.003425e+07,1.050958e+07,9.676605e+07,1.044659e+08
min,202402.0,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,...,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,-1.248090e+05,-1.248090e+05,-3.261240e+08,0.000000e+00,-3.067662e+09
25%,202402.0,3.266178e+05,3.213808e+05,0.000000e+00,0.000000e+00,0.000000e+00,1.168345e+05,0.000000e+00,0.000000e+00,0.000000e+00,...,8.980404e+06,0.000000e+00,1.252500e+02,0.000000e+00,0.000000e+00,0.000000e+00,0.000000e+00,2.281105e+05,8.539482e+05,-1.944920e+06
50%,202402.0,7.021420e+05,6.992185e+05,0.000000e+00,0.000000e+00,0.000000e+00,5.283355e+05,0.000000e+00,0.000000e+00,0.000000e+00,...,2.287770e+07,0.000000e+00,5.544454e+06,0.000000e+00,0.000000e+00,4.215000e+02,4.215000e+02,7.686295e+05,1.942939e+06,-9.183590e+05
75%,202402.0,1.184213e+06,1.178240e+06,0.000000e+00,0.000000e+00,9.415500e+03,1.557980e+06,5.805515e+06,0.000000e+00,0.000000e+00,...,5.030886e+07,0.000000e+00,3.528767e+07,0.000000e+00,0.000000e+00,3.658625e+04,3.658625e+04,1.937633e+06,4.020518e+06,-4.152650e+05
max,202402.0,9.653350e+08,4.899288e+08,5.697236e+08,5.190475e+06,8.666568e+06,1.845121e+09,2.068260e+10,3.064279e+07,2.149220e+07,...,2.776956e+10,1.490931e+10,5.407703e+10,3.780151e+07,3.747545e+08,3.324083e+08,3.324083e+08,7.937021e+07,2.949195e+09,9.467900e+04

In [21]:
estban2[lista].dtypes

VERBETE_112_DEPOSITOS_BANCARIOS                int64
VERBETE_113_BACEN_RESERV_BANC_EM_ESPECIE       int64
VERBETE_120_APLIC_INTERFINANC_DE_LIQUIDEZ     object
VERBETE_130_TIT_E_VAL_MOB_E_INST_FIN_DERIV    object
VERBETE_140_REL_INTERFINANC_E_INTERDEPEND     object
VERBETE_158_OUTR_REL_INTERF_E_INTERDEPEND     object
VERBETE_160_OPERACOES_DE_CREDITO              object
VERBETE_161_EMPRES_E_TIT_DESCONTADOS          object
VERBETE_162_FINANCIAMENTOS                     int64
VERBETE_163_FIN_RURAIS_AGRICUL_CUST/INVEST     int64
VERBETE_167_FINANCIAMENTOS_AGROINDUSTRIAIS     int64
VERBETE_169_FINANCIAMENTOS_IMOBILIARIOS       object
VERBETE_171_OUTRAS_OPERACOES_DE_CREDITO        int64
VERBETE_172_OUTROS_CREDITOS                   object
VERBETE_174_PROV_P/_OPER_CREDITOS              int64
VERBETE_176_OPERACOES_ESPECIAIS                int64
VERBETE_180_ARRENDAMENTO_MERCANTIL             int64
VERBETE_184_PROV_P/OPER_ARR_MERCANTIL          int64
VERBETE_190_OUTROS_VALORES_E_BENS              int64
VERBETE_200_PERMANENTE                        object
VERBETE_399_TOTAL_DO_ATIVO                    object
VERBETE_420_DEPOSITOS_DE_POUPANCA              int64
VERBETE_430_DEPOSITOS_INTERIFNANCEIROS        object
VERBETE_431_DEPOSITOS_INTERFINANCEIROS         int64
VERBETE_432_DEPOSITOS_A_PRAZO                  int64
VERBETE_433_CAPTACEOS_NO_MERCADO_ABERTO       object
VERBETE_440_REL_INTERFINANC_E_INTERDEPEND     object
VERBETE_460_OBRIG_POR_EMP_E_REPASSES          object
VERBETE_470_INST_FINANCEIROS_DERIVATIVOS       int64
VERBETE_480_OBRIGACOES_POR_RECEBIMENTO         int64
VERBETE_610_PATRIMONIO_LIQUIDO                object
VERBETE_711_CONTAS_CREDORAS                    int64
VERBETE_712_CONTAS_DEVEDORAS                   int64
VERBETE_899_TOTAL_DO_PASSIVO                  object
dtype: object

In [13]:
lista = [ 'VERBETE_112_DEPOSITOS_BANCARIOS','VERBETE_113_BACEN_RESERV_BANC_EM_ESPECIE','VERBETE_120_APLIC_INTERFINANC_DE_LIQUIDEZ',
          'VERBETE_130_TIT_E_VAL_MOB_E_INST_FIN_DERIV','VERBETE_140_REL_INTERFINANC_E_INTERDEPEND','VERBETE_158_OUTR_REL_INTERF_E_INTERDEPEND', 
          'VERBETE_160_OPERACOES_DE_CREDITO','VERBETE_161_EMPRES_E_TIT_DESCONTADOS','VERBETE_162_FINANCIAMENTOS',
          'VERBETE_163_FIN_RURAIS_AGRICUL_CUST/INVEST','VERBETE_167_FINANCIAMENTOS_AGROINDUSTRIAIS','VERBETE_169_FINANCIAMENTOS_IMOBILIARIOS',
          'VERBETE_171_OUTRAS_OPERACOES_DE_CREDITO','VERBETE_172_OUTROS_CREDITOS','VERBETE_174_PROV_P/_OPER_CREDITOS','VERBETE_176_OPERACOES_ESPECIAIS',
          'VERBETE_180_ARRENDAMENTO_MERCANTIL','VERBETE_184_PROV_P/OPER_ARR_MERCANTIL','VERBETE_190_OUTROS_VALORES_E_BENS',
          'VERBETE_200_PERMANENTE','VERBETE_399_TOTAL_DO_ATIVO','VERBETE_420_DEPOSITOS_DE_POUPANCA','VERBETE_430_DEPOSITOS_INTERIFNANCEIROS',
          'VERBETE_431_DEPOSITOS_INTERFINANCEIROS','VERBETE_432_DEPOSITOS_A_PRAZO','VERBETE_433_CAPTACEOS_NO_MERCADO_ABERTO',
          'VERBETE_440_REL_INTERFINANC_E_INTERDEPEND','VERBETE_460_OBRIG_POR_EMP_E_REPASSES','VERBETE_470_INST_FINANCEIROS_DERIVATIVOS',
          'VERBETE_480_OBRIGACOES_POR_RECEBIMENTO','VERBETE_610_PATRIMONIO_LIQUIDO','VERBETE_711_CONTAS_CREDORAS',
          'VERBETE_712_CONTAS_DEVEDORAS','VERBETE_899_TOTAL_DO_PASSIVO']

In [22]:
# Convertento todas as variáveis para numérica
estban2[lista] = estban2[lista].apply(pd.to_numeric, errors='coerce')

In [23]:
#estban2 = estban[estban['UF']=='RS'].copy()

In [26]:
for var in lista:
    print(estban2[var].describe())
    print('\n')

count    1.426000e+03
mean     8.210152e+05
std      1.660114e+07
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      5.697236e+08
Name: VERBETE_112_DEPOSITOS_BANCARIOS, dtype: float64


count    1.426000e+03
mean     3.862065e+03
std      1.376352e+05
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      5.190475e+06
Name: VERBETE_113_BACEN_RESERV_BANC_EM_ESPECIE, dtype: float64


count    1.426000e+03
mean     1.113312e+07
std      3.125072e+08
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      1.101396e+10
Name: VERBETE_120_APLIC_INTERFINANC_DE_LIQUIDEZ, dtype: float64


count    1.426000e+03
mean     5.923087e+07
std      1.505809e+09
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      4.690657e+10
Name: VERBETE_130_TIT_E_VAL_MOB_E_INST_FIN_DERIV, dtype: float64


count    1.426000e+03
mean     1.749928e+08
std      2.560514e+09
min     -1.752712e+09
25%      2.556475e+04
50%      6.925690e+05
75%      2.097618e+07
max      6.826980e+10
Name: VERBETE_140_REL_INTERFINANC_E_INTERDEPEND, dtype: float64


count    1.426000e+03
mean     4.533675e+07
std      1.840172e+09
min     -1.752712e+09
25%      0.000000e+00
50%      1.979000e+03
75%      3.233325e+04
max      6.826980e+10
Name: VERBETE_158_OUTR_REL_INTERF_E_INTERDEPEND, dtype: float64


count    1.426000e+03
mean     1.858615e+08
std      1.476750e+09
min      0.000000e+00
25%      1.665548e+07
50%      5.345738e+07
75%      1.475543e+08
max      4.050788e+10
Name: VERBETE_160_OPERACOES_DE_CREDITO, dtype: float64


count    1.426000e+03
mean     5.506538e+07
std      3.532372e+08
min      0.000000e+00
25%      1.030898e+07
50%      2.375662e+07
75%      4.988650e+07
max      1.217341e+10
Name: VERBETE_161_EMPRES_E_TIT_DESCONTADOS, dtype: float64


count    1.426000e+03
mean     7.976407e+06
std      7.502340e+07
min      0.000000e+00
25%      1.168345e+05
50%      5.283355e+05
75%      1.557980e+06
max      1.845121e+09
Name: VERBETE_162_FINANCIAMENTOS, dtype: float64


count    1.426000e+03
mean     5.335672e+07
std      6.357863e+08
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      5.805515e+06
max      2.068260e+10
Name: VERBETE_163_FIN_RURAIS_AGRICUL_CUST/INVEST, dtype: float64


count    1.426000e+03
mean     6.209078e+04
std      1.145097e+06
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      3.064279e+07
Name: VERBETE_167_FINANCIAMENTOS_AGROINDUSTRIAIS, dtype: float64


count    1.426000e+03
mean     4.660688e+07
std      2.167514e+08
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      7.027486e+06
max      6.132724e+09
Name: VERBETE_169_FINANCIAMENTOS_IMOBILIARIOS, dtype: float64


count    1.426000e+03
mean     1.784755e+05
std      7.692735e+05
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      2.149220e+07
Name: VERBETE_171_OUTRAS_OPERACOES_DE_CREDITO, dtype: float64


count    1.426000e+03
mean     2.691314e+07
std      4.060482e+08
min      0.000000e+00
25%      1.088250e+04
50%      1.035425e+05
75%      2.849995e+06
max      1.173611e+10
Name: VERBETE_172_OUTROS_CREDITOS, dtype: float64


count    1.426000e+03
mean    -4.297578e+06
std      7.148448e+07
min     -2.689541e+09
25%     -2.114573e+06
50%      0.000000e+00
75%      0.000000e+00
max      0.000000e+00
Name: VERBETE_174_PROV_P/_OPER_CREDITOS, dtype: float64


count    1426.0
mean        0.0
std         0.0
min         0.0
25%         0.0
50%         0.0
75%         0.0
max         0.0
Name: VERBETE_176_OPERACOES_ESPECIAIS, dtype: float64


count     1426.000000
mean        20.140954
std        760.438568
min          0.000000
25%          0.000000
50%          0.000000
75%          0.000000
max      28716.000000
Name: VERBETE_180_ARRENDAMENTO_MERCANTIL, dtype: float64


count      1426.000000
mean       -466.725105
std       17624.667196
min     -665550.000000
25%           0.000000
50%           0.000000
75%           0.000000
max           0.000000
Name: VERBETE_184_PROV_P/OPER_ARR_MERCANTIL, dtype: float64


count    1.426000e+03
mean     4.547572e+05
std      6.916438e+06
min      0.000000e+00
25%      0.000000e+00
50%      7.085500e+03
75%      3.223650e+04
max      2.513078e+08
Name: VERBETE_190_OUTROS_VALORES_E_BENS, dtype: float64


count    1.426000e+03
mean     3.294672e+06
std      1.187653e+08
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      4.481171e+09
Name: VERBETE_200_PERMANENTE, dtype: float64


count    1.424000e+03
mean     2.517241e+08
std      1.773694e+09
min      0.000000e+00
25%      3.302601e+07
50%      8.001163e+07
75%      1.798380e+08
max      4.754646e+10
Name: VERBETE_399_TOTAL_DO_ATIVO, dtype: float64


count    1.426000e+03
mean     6.114234e+07
std      7.366360e+08
min      0.000000e+00
25%      8.980404e+06
50%      2.287770e+07
75%      5.030886e+07
max      2.776956e+10
Name: VERBETE_420_DEPOSITOS_DE_POUPANCA, dtype: float64


count    1.426000e+03
mean     1.305456e+08
std      2.201100e+09
min      0.000000e+00
25%      1.252500e+02
50%      5.544454e+06
75%      3.528767e+07
max      7.518505e+10
Name: VERBETE_430_DEPOSITOS_INTERIFNANCEIROS, dtype: float64


count    1.426000e+03
mean     1.213130e+07
std      3.998152e+08
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      1.490931e+10
Name: VERBETE_431_DEPOSITOS_INTERFINANCEIROS, dtype: float64


count    1.426000e+03
mean     9.630509e+07
std      1.463303e+09
min      0.000000e+00
25%      1.252500e+02
50%      5.544454e+06
75%      3.528767e+07
max      5.407703e+10
Name: VERBETE_432_DEPOSITOS_A_PRAZO, dtype: float64


count    1.426000e+03
mean     2.210920e+07
std      5.983854e+08
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      1.871810e+10
Name: VERBETE_433_CAPTACEOS_NO_MERCADO_ABERTO, dtype: float64


count    1.426000e+03
mean     1.350703e+08
std      1.766837e+09
min      0.000000e+00
25%      1.114485e+05
50%      2.101470e+06
75%      2.032273e+07
max      4.754689e+10
Name: VERBETE_440_REL_INTERFINANC_E_INTERDEPEND, dtype: float64


count    1.426000e+03
mean     2.663413e+07
std      8.457267e+08
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      3.176066e+10
Name: VERBETE_460_OBRIG_POR_EMP_E_REPASSES, dtype: float64


count    1.426000e+03
mean     2.722413e+05
std      9.930027e+06
min      0.000000e+00
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      3.747545e+08
Name: VERBETE_470_INST_FINANCEIROS_DERIVATIVOS, dtype: float64


count    1.426000e+03
mean     6.007647e+05
std      1.003425e+07
min     -1.248090e+05
25%      0.000000e+00
50%      4.215000e+02
75%      3.658625e+04
max      3.324083e+08
Name: VERBETE_480_OBRIGACOES_POR_RECEBIMENTO, dtype: float64


count    1.426000e+03
mean     9.847197e+06
std      2.655098e+08
min     -4.272799e+07
25%      0.000000e+00
50%      0.000000e+00
75%      0.000000e+00
max      9.660924e+09
Name: VERBETE_610_PATRIMONIO_LIQUIDO, dtype: float64


count    1.426000e+03
mean     7.123567e+06
std      9.676605e+07
min      0.000000e+00
25%      8.539482e+05
50%      1.942939e+06
75%      4.020518e+06
max      2.949195e+09
Name: VERBETE_711_CONTAS_CREDORAS, dtype: float64


count    1.426000e+03
mean    -5.914392e+06
std      1.044659e+08
min     -3.067662e+09
25%     -1.944920e+06
50%     -9.183590e+05
75%     -4.152650e+05
max      9.467900e+04
Name: VERBETE_712_CONTAS_DEVEDORAS, dtype: float64


count    1.424000e+03
mean     2.517241e+08
std      1.773694e+09
min      0.000000e+00
25%      3.302601e+07
50%      8.001163e+07
75%      1.798380e+08
max      4.754646e+10
Name: VERBETE_899_TOTAL_DO_PASSIVO, dtype: float64

In [65]:
#bancos2 = bancos.merge(covid[["Domicilios_%","id"]]	, on=id)

estban3 = estban2.merge(covid[["Domicilios_%","id"]]	, on="id")

In [67]:
estban3['FINANCIAMENTOS_afetadas']  = estban3['FINANCIAMENTOS']*estban3['Domicilios_%']/100
#estban3['postos_elet_afetados']  = estban3['countPAE']*bancos2['Domicilios_%']/100
#estban3['postos_atend_afetados'] = estban3['countPOSTOS']*bancos2['Domicilios_%']/100

In [70]:
estban3['FINANCIAMENTOS_afetadas'].describe()

count    7.610000e+02
mean     1.526734e+06
std      1.249363e+07
min      0.000000e+00
25%      5.245000e+00
50%      1.634469e+04
75%      1.187187e+05
max      2.287951e+08
Name: FINANCIAMENTOS_afetadas, dtype: float64