In [1]:
from bs4 import BeautifulSoup
from selenium import webdriver
import time
import pandas as pd
import numpy as np

In [ ]:
mainlist = []
infile = open('listalab.txt','r')
for line in infile:
    mainlist.append(line.strip().split(','))

infile.close()

print(mainlist)
lista = []
for item  in mainlist:
    print(item[0],item[0][12:])
    lista.append(item[0][12:])

In [ ]:
lista

In [32]:
from pathlib import Path
import glob
import pandas as pd


# Get data file names
path = r'C:\\Users\\patrick.franco\\Documents\\GitHub\\enchentes\\webscraping'
filenames = glob.glob(path + "/df*.csv")

dfs = []
for filename in filenames:
    dfs.append(pd.read_csv(filename))

# Concatenate all data into one DataFrame
big_frame = pd.concat(dfs, ignore_index=True)

In [47]:
#big_frame.rename(columns={'num_mcti':'lab','site':'site_lab'},inplace=True)
#big_frame.drop(columns=['Unnamed: 0'],axis=1,inplace=True)
big_frame['site_mcti'] = "https://pnipe.mcti.gov.br/laboratory/" + big_frame['lab'].astype(str)

big_frame2 = big_frame[['lab','site_mcti','nome', 'tel','endereco','cidade', 'cep', 'email','site_lab','sobre']].copy()

In [83]:
#big_frame.to_csv("C:\\Users\\patrick.franco\\Documents\\GitHub\\enchentes\\webscraping\\big_frame.csv", encoding="utf-8-sig")
big_frame2.to_excel("C:\\Users\\patrick.franco\\Documents\\GitHub\\enchentes\\webscraping\\big_frame2.xlsx", 
encoding="utf-8-sig",sheet_name="cadatro_nomes")

c:\Users\patrick.franco\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\util\_decorators.py:211: FutureWarning: the 'encoding' keyword is deprecated and will be removed in a future version. Please take steps to stop the use of 'encoding'
  return func(*args, **kwargs)

In [50]:
big_frame.head()

,lab,sobre,endereco,cidade,cep,nome,tel,email,site_lab,site_mcti
0,10006,Utilizado para o desenvolvimento de pesquisas ...,Professor Lineu Prestes,São Paulo - SP - 580,Veja como chegar,Mario Hiroyuki Hirata,(55) 11998-3877,NaN,NaN,https://pnipe.mcti.gov.br/laboratory/10006
1,10008,O laboratório de biossegurança Nível 3 do Depa...,Professor Lineu Prestes,São Paulo - SP - 580,Veja como chegar,Mario Hiroyuki Hirata,(55) 11998-3877,mhhirata@usp.br,https://uspmulti.prp.usp.br/public/centrais/126,https://pnipe.mcti.gov.br/laboratory/10008
2,10037,Trata-se de biotério utilizado pelos pesquisad...,Professor Lineu Prestes,São Paulo - SP - 1524,Veja como chegar,Eliana Akamine,(11) 3091-7317,biot.farmaco@icb.usp.br,NaN,https://pnipe.mcti.gov.br/laboratory/10037
3,1004,Laboratório de pesquisa em neurobiologia com ê...,Rua José Lourenço Kelmer,Juiz de Fora - MG - s/n,Veja como chegar,Bruno Siqueira Mietto,(21) 99934-0074,bruno.mietto@ufjf.edu.br,NaN,https://pnipe.mcti.gov.br/laboratory/1004
4,10057,Os laboratórios de Química Analítica e Radiome...,Poços de Caldas - Andradas,Poços de Caldas - MG - km13,Veja como chegar,Rodrigo Leandro Bonifácio,(35) 3716-7029,lapoc@cnen.gov.br,http://www.cnenpc.gov.br,https://pnipe.mcti.gov.br/laboratory/10057

In [30]:
#big_frame['site_mcti'] = "https://pnipe.mcti.gov.br/laboratory/" + str(big_frame['lab'].astype('Int64'))
#big_frame['site_mcti'] = big_frame['lab'].astype('Int64')
big_frame['site_mcti'] = "https://pnipe.mcti.gov.br/laboratory/" + str(big_frame['num_mcti'])

In [18]:
#big_frame.drop(columns=['Unnamed: 0'],axis=1,inplace=True)

In [ ]:
#big_frame.rename(columns={'num_mcti':'lab','site':'site_lab'},inplace=True)

In [24]:
big_frame2 = big_frame[['lab','site_mcti','sobre', 'endereco', 'cidade', 'cep', 'nome', 'tel', 'email','site_lab']].copy()

In [26]:
big_frame2.head()

,lab,site_mcti,sobre,endereco,cidade,cep,nome,tel,email,site_lab
0,10006,https://pnipe.mcti.gov.br/laboratory/0 1...,Utilizado para o desenvolvimento de pesquisas ...,Professor Lineu Prestes,São Paulo - SP - 580,Veja como chegar,Mario Hiroyuki Hirata,(55) 11998-3877,NaN,NaN
1,10008,https://pnipe.mcti.gov.br/laboratory/0 1...,O laboratório de biossegurança Nível 3 do Depa...,Professor Lineu Prestes,São Paulo - SP - 580,Veja como chegar,Mario Hiroyuki Hirata,(55) 11998-3877,mhhirata@usp.br,https://uspmulti.prp.usp.br/public/centrais/126
2,10037,https://pnipe.mcti.gov.br/laboratory/0 1...,Trata-se de biotério utilizado pelos pesquisad...,Professor Lineu Prestes,São Paulo - SP - 1524,Veja como chegar,Eliana Akamine,(11) 3091-7317,biot.farmaco@icb.usp.br,NaN
3,1004,https://pnipe.mcti.gov.br/laboratory/0 1...,Laboratório de pesquisa em neurobiologia com ê...,Rua José Lourenço Kelmer,Juiz de Fora - MG - s/n,Veja como chegar,Bruno Siqueira Mietto,(21) 99934-0074,bruno.mietto@ufjf.edu.br,NaN
4,10057,https://pnipe.mcti.gov.br/laboratory/0 1...,Os laboratórios de Química Analítica e Radiome...,Poços de Caldas - Andradas,Poços de Caldas - MG - km13,Veja como chegar,Rodrigo Leandro Bonifácio,(35) 3716-7029,lapoc@cnen.gov.br,http://www.cnenpc.gov.br

In [70]:
mainlist = []
infile = open('listalab.txt','r')
for line in infile:
    mainlist.append(line.strip().split(','))

lista1 = []
for item  in mainlist:
    lista1.append(int(item[0][12:]))

In [ ]:
lista1

In [72]:
lista2 = list(big_frame2['lab'])

In [ ]:
lista2

In [74]:
#new_list = list(set(list(big_frame2['lab'])).difference(lista))
new_list = list(set(lista1).difference(lista2))

In [75]:
len(new_list)

198

In [84]:
df_nao = pd.DataFrame({'lab':new_list})
df_nao['site_mcti'] = "https://pnipe.mcti.gov.br/laboratory/" + df_nao['lab'].astype(str)

In [85]:
df_nao.head()

     lab                                   site_mcti
0  24580  https://pnipe.mcti.gov.br/laboratory/24580
1  24583  https://pnipe.mcti.gov.br/laboratory/24583
2  18441  https://pnipe.mcti.gov.br/laboratory/18441
3   8210   https://pnipe.mcti.gov.br/laboratory/8210
4  27667  https://pnipe.mcti.gov.br/laboratory/27667

In [86]:
#big_frame.to_csv("C:\\Users\\patrick.franco\\Documents\\GitHub\\enchentes\\webscraping\\big_frame.csv", encoding="utf-8-sig")
df_nao.to_excel("C:\\Users\\patrick.franco\\Documents\\GitHub\\enchentes\\webscraping\\nao_encontrado.xlsx", 
encoding="utf-8-sig",sheet_name="nao_encontrado")

c:\Users\patrick.franco\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\util\_decorators.py:211: FutureWarning: the 'encoding' keyword is deprecated and will be removed in a future version. Please take steps to stop the use of 'encoding'
  return func(*args, **kwargs)

In [90]:
from pathlib import Path
import glob
import pandas as pd


# Get data file names
path = r'C:\\Users\\patrick.franco\\Documents\\GitHub\\enchentes\\webscraping'
filenames = glob.glob(path + "/cods*.csv")

dfs = []
for filename in filenames:
    dfs.append(pd.read_csv(filename))

# Concatenate all data into one DataFrame
cod_equip = pd.concat(dfs, ignore_index=True)
cod_equip['fica'] = cod_equip['codigos'].str.slice(0, 3)
cod_equip['site_mcti'] = "https://pnipe.mcti.gov.br/laboratory/" + cod_equip['lab'].astype(str)

In [92]:
#cod_equip.rename[['site_mcti','lab','codigos']][cod_equip['fica']=='Cod'].head()

,Unnamed: 0,codigos,lab,fica,site_mcti
0,0,NaN,10006,NaN,https://pnipe.mcti.gov.br/laboratory/10006
1,1,Cod29G3ZW/22,10006,Cod,https://pnipe.mcti.gov.br/laboratory/10006
2,2,Analisador de ácidos nucleicos TapeStation 2200,10006,Ana,https://pnipe.mcti.gov.br/laboratory/10006
3,3,Agilent Technologies,10006,Agi,https://pnipe.mcti.gov.br/laboratory/10006
4,4,2200,10006,220,https://pnipe.mcti.gov.br/laboratory/10006

In [95]:
cod_equip2 = cod_equip[['site_mcti','lab','codigos']][cod_equip['fica']=='Cod'].copy()

In [96]:
cod_equip2.head()

                                     site_mcti    lab       codigos
1   https://pnipe.mcti.gov.br/laboratory/10006  10006  Cod29G3ZW/22
6   https://pnipe.mcti.gov.br/laboratory/10006  10006  Cod0XA11S/22
11  https://pnipe.mcti.gov.br/laboratory/10006  10006  Cod44ZD3D/22
16  https://pnipe.mcti.gov.br/laboratory/10006  10006  Cod3KV65S/22
21  https://pnipe.mcti.gov.br/laboratory/10008  10008  Cod7G4LW0/22

In [97]:
#big_frame.to_csv("C:\\Users\\patrick.franco\\Documents\\GitHub\\enchentes\\webscraping\\big_frame.csv", encoding="utf-8-sig")
cod_equip2.to_excel("C:\\Users\\patrick.franco\\Documents\\GitHub\\enchentes\\webscraping\\cod_equip2.xlsx", 
encoding="utf-8-sig",sheet_name="codigos_equipamentos")

c:\Users\patrick.franco\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\util\_decorators.py:211: FutureWarning: the 'encoding' keyword is deprecated and will be removed in a future version. Please take steps to stop the use of 'encoding'
  return func(*args, **kwargs)

In [100]:
from pathlib import Path
import glob
import pandas as pd


# Get data file names
path = r'C:\\Users\\patrick.franco\\Documents\\GitHub\\enchentes\\webscraping'
filenames = glob.glob(path + "/area*.csv")

dfs = []
for filename in filenames:
    dfs.append(pd.read_csv(filename))

# Concatenate all data into one DataFrame
df_areas = pd.concat(dfs, ignore_index=True)
#cod_equip['fica'] = cod_equip['codigos'].str.slice(0, 3)
df_areas['site_mcti'] = "https://pnipe.mcti.gov.br/laboratory/" + cod_equip['lab'].astype(str)

In [101]:
df_areas.head()

,Unnamed: 0,areas,lab,site_mcti
0,0,Genômica,10006,https://pnipe.mcti.gov.br/laboratory/10006
1,1,Proteômica,10006,https://pnipe.mcti.gov.br/laboratory/10006
2,2,Epigenômica,10006,https://pnipe.mcti.gov.br/laboratory/10006
3,3,sequenciador Miseq (Illumina),10006,https://pnipe.mcti.gov.br/laboratory/10006
4,4,Luminex,10006,https://pnipe.mcti.gov.br/laboratory/10006

In [102]:
df_areas2 = df_areas[['site_mcti','lab','areas']].copy()

In [104]:
#big_frame.to_csv("C:\\Users\\patrick.franco\\Documents\\GitHub\\enchentes\\webscraping\\big_frame.csv", encoding="utf-8-sig")
df_areas2.to_excel("C:\\Users\\patrick.franco\\Documents\\GitHub\\enchentes\\webscraping\\areas.xlsx", 
encoding="utf-8-sig",sheet_name="areas_labs")

In [ ]:
################

In [1]:
from bs4 import BeautifulSoup
from selenium import webdriver
import time
import pandas as pd
import numpy as np

In [2]:
webdriver = webdriver.Chrome()
webdriver.execute_script("window.scrollTo(0, document.body.scrollHeight);")


url = 'https://pnipe.mcti.gov.br/laboratory/10008' 
    
webdriver.get(url)
time.sleep(2)    
soup = BeautifulSoup(webdriver.page_source,'html.parser')

In [13]:
nomes = soup.find_all('div', attrs={'class':'MuiBox-root jss58'})
datas = soup.find_all('p', attrs={'class':'MuiTypography-root MuiTypography-body1 MuiTypography-colorTextPrimary MuiTypography-noWrap'})
univs = soup.find_all('p', attrs={'class':'MuiTypography-root MuiTypography-body1 MuiTypography-colorTextPrimary'})

In [9]:
for nome in nomes:
    print(nome.get_text())

NB3 - Laboratório Multiusuário com Nivel de Biossegurança 3 - LMB-NB3

In [12]:
for data in datas:
    print(data.get_text())

Data de criação: 17/03/2022

In [14]:
for univ in univs:
    print(univ.get_text())

USP - Universidade de São Paulo

## Organizar Dados com os Nomes

In [58]:
from pathlib import Path
import glob
import pandas as pd

# Get data file names
path = r'C:\\Users\\patrick.franco\\Documents\\GitHub\\enchentes\\webscraping'
filenames1 = glob.glob(path + "/nomes*.csv")

dfs = []
for filename in filenames1:
    dfs.append(pd.read_csv(filename))

# Concatenate all data into one DataFrame
df_nomes = pd.concat(dfs, ignore_index=True)
#cod_equip['fica'] = cod_equip['codigos'].str.slice(0, 3)
df_nomes['site_mcti'] = "https://pnipe.mcti.gov.br/laboratory/" + df_nomes['lab'].astype(str)


# Get data file names
filenames2 = glob.glob(path + "/df*.csv")

dfs = []
for filename in filenames2:
    dfs.append(pd.read_csv(filename))

# Concatenate all data into one DataFrame
big_frame = pd.concat(dfs, ignore_index=True)

In [59]:
#df_nomes['data_de_criacao'] = df_nomes['data_criacao'].str.slice(13, 10)
df_nomes['data_de_criacao'] = df_nomes['data_criacao'].str.replace(r'Data de criação:', '', regex=True)

df_nomes.rename(columns={'nome':'nome_lab'},inplace=True)

In [60]:
df_nomes.head()

,Unnamed: 0,nome_lab,data_criacao,universidade,lab,site_mcti,data_de_criacao
0,0,CTO - Centro de Tecnologias Ômicas,Data de criação: 17/03/2022,USP - Universidade de São Paulo,10006,https://pnipe.mcti.gov.br/laboratory/10006,17/03/2022
1,0,NB3 - Laboratório Multiusuário com Nivel de Bi...,Data de criação: 17/03/2022,USP - Universidade de São Paulo,10008,https://pnipe.mcti.gov.br/laboratory/10008,17/03/2022
2,0,IA BMF - ICB/USP - Instalação Animal do Depart...,Data de criação: 18/03/2022,USP - Universidade de São Paulo,10037,https://pnipe.mcti.gov.br/laboratory/10037,18/03/2022
3,0,Mietto Lab - Lab. de Biologia Celular,Data de criação: 22/09/2020,UFJF - Universidade Federal de Juiz de Fora,1004,https://pnipe.mcti.gov.br/laboratory/1004,22/09/2020
4,0,QA/SECTEC/LAPOC - Laboratório de Radiometria e...,Data de criação: 21/03/2022,CNEN - Comissão Nacional de Energia Nuclear,10057,https://pnipe.mcti.gov.br/laboratory/10057,21/03/2022

In [61]:
big_frame.rename(columns={'num_mcti':'lab','site':'site_lab','nome':'nome_responsavel'},inplace=True)
#big_frame.drop(columns=['Unnamed: 0'],axis=1,inplace=True)
big_frame['site_mcti'] = "https://pnipe.mcti.gov.br/laboratory/" + big_frame['lab'].astype(str)

In [62]:
big_frame.head()

,Unnamed: 0,lab,sobre,endereco,cidade,cep,nome_responsavel,tel,email,site_lab,site_mcti
0,0,10006,Utilizado para o desenvolvimento de pesquisas ...,Professor Lineu Prestes,São Paulo - SP - 580,Veja como chegar,Mario Hiroyuki Hirata,(55) 11998-3877,NaN,NaN,https://pnipe.mcti.gov.br/laboratory/10006
1,0,10008,O laboratório de biossegurança Nível 3 do Depa...,Professor Lineu Prestes,São Paulo - SP - 580,Veja como chegar,Mario Hiroyuki Hirata,(55) 11998-3877,mhhirata@usp.br,https://uspmulti.prp.usp.br/public/centrais/126,https://pnipe.mcti.gov.br/laboratory/10008
2,0,10037,Trata-se de biotério utilizado pelos pesquisad...,Professor Lineu Prestes,São Paulo - SP - 1524,Veja como chegar,Eliana Akamine,(11) 3091-7317,biot.farmaco@icb.usp.br,NaN,https://pnipe.mcti.gov.br/laboratory/10037
3,0,1004,Laboratório de pesquisa em neurobiologia com ê...,Rua José Lourenço Kelmer,Juiz de Fora - MG - s/n,Veja como chegar,Bruno Siqueira Mietto,(21) 99934-0074,bruno.mietto@ufjf.edu.br,NaN,https://pnipe.mcti.gov.br/laboratory/1004
4,0,10057,Os laboratórios de Química Analítica e Radiome...,Poços de Caldas - Andradas,Poços de Caldas - MG - km13,Veja como chegar,Rodrigo Leandro Bonifácio,(35) 3716-7029,lapoc@cnen.gov.br,http://www.cnenpc.gov.br,https://pnipe.mcti.gov.br/laboratory/10057

In [63]:
big_frame2 = big_frame.merge(df_nomes, on=['lab','site_mcti'])

In [64]:
big_frame2.head()

,Unnamed: 0_x,lab,sobre,endereco,cidade,cep,nome_responsavel,tel,email,site_lab,site_mcti,Unnamed: 0_y,nome_lab,data_criacao,universidade,data_de_criacao
0,0,10006,Utilizado para o desenvolvimento de pesquisas ...,Professor Lineu Prestes,São Paulo - SP - 580,Veja como chegar,Mario Hiroyuki Hirata,(55) 11998-3877,NaN,NaN,https://pnipe.mcti.gov.br/laboratory/10006,0,CTO - Centro de Tecnologias Ômicas,Data de criação: 17/03/2022,USP - Universidade de São Paulo,17/03/2022
1,0,10008,O laboratório de biossegurança Nível 3 do Depa...,Professor Lineu Prestes,São Paulo - SP - 580,Veja como chegar,Mario Hiroyuki Hirata,(55) 11998-3877,mhhirata@usp.br,https://uspmulti.prp.usp.br/public/centrais/126,https://pnipe.mcti.gov.br/laboratory/10008,0,NB3 - Laboratório Multiusuário com Nivel de Bi...,Data de criação: 17/03/2022,USP - Universidade de São Paulo,17/03/2022
2,0,10037,Trata-se de biotério utilizado pelos pesquisad...,Professor Lineu Prestes,São Paulo - SP - 1524,Veja como chegar,Eliana Akamine,(11) 3091-7317,biot.farmaco@icb.usp.br,NaN,https://pnipe.mcti.gov.br/laboratory/10037,0,IA BMF - ICB/USP - Instalação Animal do Depart...,Data de criação: 18/03/2022,USP - Universidade de São Paulo,18/03/2022
3,0,1004,Laboratório de pesquisa em neurobiologia com ê...,Rua José Lourenço Kelmer,Juiz de Fora - MG - s/n,Veja como chegar,Bruno Siqueira Mietto,(21) 99934-0074,bruno.mietto@ufjf.edu.br,NaN,https://pnipe.mcti.gov.br/laboratory/1004,0,Mietto Lab - Lab. de Biologia Celular,Data de criação: 22/09/2020,UFJF - Universidade Federal de Juiz de Fora,22/09/2020
4,0,10057,Os laboratórios de Química Analítica e Radiome...,Poços de Caldas - Andradas,Poços de Caldas - MG - km13,Veja como chegar,Rodrigo Leandro Bonifácio,(35) 3716-7029,lapoc@cnen.gov.br,http://www.cnenpc.gov.br,https://pnipe.mcti.gov.br/laboratory/10057,0,QA/SECTEC/LAPOC - Laboratório de Radiometria e...,Data de criação: 21/03/2022,CNEN - Comissão Nacional de Energia Nuclear,21/03/2022

In [65]:
big_frame2.columns

Index(['Unnamed: 0_x', 'lab', 'sobre', 'endereco', 'cidade', 'cep',
       'nome_responsavel', 'tel', 'email', 'site_lab', 'site_mcti',
       'Unnamed: 0_y', 'nome_lab', 'data_criacao', 'universidade',
       'data_de_criacao'],
      dtype='object')

In [66]:
big_frame3 = big_frame2[['lab','site_mcti','nome_lab','data_de_criacao','universidade','nome_responsavel',
'tel','endereco','cidade', 'cep','email','site_lab','sobre']].copy()

In [67]:
big_frame3.head()

,lab,site_mcti,nome_lab,data_de_criacao,universidade,nome_responsavel,tel,endereco,cidade,cep,email,site_lab,sobre
0,10006,https://pnipe.mcti.gov.br/laboratory/10006,CTO - Centro de Tecnologias Ômicas,17/03/2022,USP - Universidade de São Paulo,Mario Hiroyuki Hirata,(55) 11998-3877,Professor Lineu Prestes,São Paulo - SP - 580,Veja como chegar,NaN,NaN,Utilizado para o desenvolvimento de pesquisas ...
1,10008,https://pnipe.mcti.gov.br/laboratory/10008,NB3 - Laboratório Multiusuário com Nivel de Bi...,17/03/2022,USP - Universidade de São Paulo,Mario Hiroyuki Hirata,(55) 11998-3877,Professor Lineu Prestes,São Paulo - SP - 580,Veja como chegar,mhhirata@usp.br,https://uspmulti.prp.usp.br/public/centrais/126,O laboratório de biossegurança Nível 3 do Depa...
2,10037,https://pnipe.mcti.gov.br/laboratory/10037,IA BMF - ICB/USP - Instalação Animal do Depart...,18/03/2022,USP - Universidade de São Paulo,Eliana Akamine,(11) 3091-7317,Professor Lineu Prestes,São Paulo - SP - 1524,Veja como chegar,biot.farmaco@icb.usp.br,NaN,Trata-se de biotério utilizado pelos pesquisad...
3,1004,https://pnipe.mcti.gov.br/laboratory/1004,Mietto Lab - Lab. de Biologia Celular,22/09/2020,UFJF - Universidade Federal de Juiz de Fora,Bruno Siqueira Mietto,(21) 99934-0074,Rua José Lourenço Kelmer,Juiz de Fora - MG - s/n,Veja como chegar,bruno.mietto@ufjf.edu.br,NaN,Laboratório de pesquisa em neurobiologia com ê...
4,10057,https://pnipe.mcti.gov.br/laboratory/10057,QA/SECTEC/LAPOC - Laboratório de Radiometria e...,21/03/2022,CNEN - Comissão Nacional de Energia Nuclear,Rodrigo Leandro Bonifácio,(35) 3716-7029,Poços de Caldas - Andradas,Poços de Caldas - MG - km13,Veja como chegar,lapoc@cnen.gov.br,http://www.cnenpc.gov.br,Os laboratórios de Química Analítica e Radiome...

In [68]:
big_frame3.to_excel("C:\\Users\\patrick.franco\\Documents\\GitHub\\enchentes\\webscraping\\big_frame.xlsx", 
encoding="utf-8-sig",sheet_name="codigos_equipamentos")

c:\Users\patrick.franco\AppData\Local\Programs\Python\Python311\Lib\site-packages\pandas\util\_decorators.py:211: FutureWarning: the 'encoding' keyword is deprecated and will be removed in a future version. Please take steps to stop the use of 'encoding'
  return func(*args, **kwargs)

In [27]:
#https://stackoverflow.com/questions/70764097/how-can-i-ping-a-specific-port-and-report-the-results
import socket
import random
import time
#print(random.randint(0,3))

def check(host,port,timeout=2):
    sock = socket.socket(socket.AF_INET,socket.SOCK_STREAM) #presumably 
    sock.settimeout(timeout)
    try:
       sock.connect((host,port))
    except:
       return False
    else:
       sock.close()
       return True

#print(check('10.221.2.9',5558,timeout=1))


#Check port open for range of ports
#https://pandeysudhendu.medium.com/using-python-to-check-tcp-socket-connectivity-8384a036833c
for i in range(50300,50599):
    time.sleep(random.randint(0,3))
    print(i,':',check('10.221.2.9',i,timeout=1))

50100 : False
50101 : False
50102 : False
50103 : False
50104 : False
50105 : False
50106 : False
50107 : False
50108 : False
50109 : False
50110 : False
50111 : False
50112 : False
50113 : False
50114 : False
50115 : False
50116 : False
50117 : False
50118 : False
50119 : False
50120 : False
50121 : False
50122 : False
50123 : False
50124 : False
50125 : False
50126 : False
50127 : False
50128 : False
50129 : False
50130 : False
50131 : False
50132 : False
50133 : False
50134 : False
50135 : False
50136 : False
50137 : False
50138 : False
50139 : False
50140 : False
50141 : False
50142 : False
50143 : False
50144 : False
50145 : False
50146 : False
50147 : False
50148 : False
50149 : False
50150 : False
50151 : False
50152 : False
50153 : False
50154 : False
50155 : False
50156 : False
50157 : False
50158 : False
50159 : False
50160 : False
50161 : False
50162 : False
50163 : False
50164 : False
50165 : False
50166 : False
50167 : False
50168 : False
50169 : False
50170 : False
50171 : False
50172 : False
50173 : False
50174 : False
50175 : False
50176 : False
50177 : False
50178 : False
50179 : False
50180 : False
50181 : False
50182 : False
50183 : False
50184 : False
50185 : False
50186 : False
50187 : False
50188 : False
50189 : False
50190 : False
50191 : False
50192 : False
50193 : False
50194 : False
50195 : False
50196 : False
50197 : False
50198 : False
50199 : False
50200 : False
50201 : False
50202 : False
50203 : False
50204 : False
50205 : False
50206 : False
50207 : False
50208 : False
50209 : False
50210 : False
50211 : False
50212 : False
50213 : False
50214 : False
50215 : False
50216 : False
50217 : False
50218 : False
50219 : False
50220 : False
50221 : False
50222 : False
50223 : False
50224 : False
50225 : False
50226 : False
50227 : False
50228 : False
50229 : False
50230 : False
50231 : False
50232 : False
50233 : False
50234 : False
50235 : False
50236 : False
50237 : False
50238 : False
50239 : False
50240 : False
50241 : False
50242 : False
50243 : False
50244 : False
50245 : False
50246 : False
50247 : False
50248 : False
50249 : False
50250 : False
50251 : False
50252 : False
50253 : False
50254 : False
50255 : False
50256 : False
50257 : False
50258 : False
50259 : False
50260 : False
50261 : False
50262 : False
50263 : False
50264 : False
50265 : False
50266 : False
50267 : False
50268 : False
50269 : False
50270 : False
50271 : False
50272 : False
50273 : False
50274 : False
50275 : False
50276 : False
50277 : False
50278 : False
50279 : False
50280 : False
50281 : False
50282 : False
50283 : False
50284 : False
50285 : False
50286 : False
50287 : False
50288 : False
50289 : False
50290 : False
50291 : False
50292 : False
50293 : False
50294 : False
50295 : False
50296 : False
50297 : False
50298 : False

In [18]:
import socket
import time
import random

def check_port(port):
    import socket, errno
    s = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
    random.randint(0,3)
    try:        
        s.bind(("127.0.0.1", port))
    except socket.error as e:
        if e.errno == errno.EADDRINUSE:
            print("Port is already in use", port)
        else:
            print(e)
            print(f"****Port: {port} cannot be acessed****")
            return False
    s.close()
    return True

# Check port open for range of ports
for i in range (1000):
    random.randint(0,3)
    check_port(i)
    print()

[WinError 10013] Foi feita uma tentativa de acesso a um soquete de uma maneira que é proibida pelas permissões de acesso
****Port: 135 cannot be acessed****






















































































































































































































































































































[WinError 10013] Foi feita uma tentativa de acesso a um soquete de uma maneira que é proibida pelas permissões de acesso
****Port: 445 cannot be acessed****